import type { LearningTopic } from './learningTypes'

export const LEARNING_TOPICS: LearningTopic[] = [
  // ── Topic 1: Circle Equations ────────────────────────────────────────────────
  {
    id: 'circles-standard-form',
    title: 'Circle Equations — Standard Form',
    subjectId: 'zol-mathematics',
    description: 'Graph circles from (x − h)² + (y − k)² = r² by placing centre and radius',
    steps: [
      {
        id: 'cir-1',
        stepNumber: 1,
        title: 'Origin circle',
        instruction: 'Graph the circle.',
        equation: 'x² + y² = 9',
        widgetType: 'circle-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { center: { x: 0, y: 0 }, radius: 3 },
        milestone: 'Finding the centre',
        hints: [
          "No (x − h) or (y − k) shifts — so where must the centre be?",
          "Centre is (0, 0). r² = 9 so drag the handle until the circle passes through (3, 0).",
        ],
      },
      {
        id: 'cir-2',
        stepNumber: 2,
        title: 'Shifted x',
        instruction: 'Graph the circle.',
        equation: '(x − 1)² + y² = 25',
        widgetType: 'circle-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { center: { x: 1, y: 0 }, radius: 5 },
        milestone: 'Shifted centre',
        hints: [
          "Form is (x − h)² + (y − k)² = r². What are h and k here?",
          "h = 1, k = 0 → centre (1, 0). r² = 25 → r = 5.",
        ],
      },
      {
        id: 'cir-3',
        stepNumber: 3,
        title: 'Shifted both axes',
        instruction: 'Graph the circle.',
        equation: '(x + 2)² + (y − 3)² = 16',
        widgetType: 'circle-graph',
        widgetConfig: { gridRange: 10 },
        correctState: { center: { x: -2, y: 3 }, radius: 4 },
        milestone: 'Two-axis shift',
        hints: [
          "(x + 2)² = (x − (−2))², so h = −2.",
          "Centre (−2, 3), r = √16 = 4.",
        ],
      },
      {
        id: 'cir-4',
        stepNumber: 4,
        title: 'Full equation',
        instruction: 'Graph the circle.',
        equation: '(x − 3)² + (y + 1)² = 36',
        widgetType: 'circle-graph',
        widgetConfig: { gridRange: 12 },
        correctState: { center: { x: 3, y: -1 }, radius: 6 },
        milestone: 'Full curve — nailed it',
        hints: [
          "h = 3, k = −1 → centre (3, −1).",
          "r² = 36 → r = 6.",
        ],
      },
    ],
  },

  // ── Topic 2: Straight Line Graphs ────────────────────────────────────────────
  {
    id: 'linear-graphs',
    title: 'Straight Line Graphs',
    subjectId: 'zol-mathematics',
    description: 'Draw lines from y = mx + c — the backbone of ZIMSEC algebra',
    steps: [
      {
        id: 'lin-1',
        stepNumber: 1,
        title: 'Through the origin',
        instruction: 'Draw the straight line.',
        equation: 'y = 2x',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: 2, intercept: 0 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Lines through the origin',
        hints: [
          "y = 2x has no + c term, so the y-intercept is 0 — the line passes through the origin.",
          "Gradient m = 2 means rise 2 for every 1 across. Keep the intercept at 0 and drag the slope handle up.",
        ],
      },
      {
        id: 'lin-2',
        stepNumber: 2,
        title: 'Positive intercept',
        instruction: 'Draw the straight line.',
        equation: 'y = x + 3',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 7 },
        correctState: { slope: 1, intercept: 3 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Positive intercept',
        hints: [
          "The line cuts the y-axis at +3 — drag the intercept handle to 3.",
          "Gradient m = 1 means a 45° rise. The slope handle should be at the same height above the intercept for every unit across.",
        ],
      },
      {
        id: 'lin-3',
        stepNumber: 3,
        title: 'Negative gradient',
        instruction: 'Draw the straight line.',
        equation: 'y = −x + 2',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: -1, intercept: 2 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Negative gradient',
        hints: [
          "c = 2, so the y-intercept is at (0, 2). The gradient m = −1 means the line slopes downward.",
          "Drag the slope handle BELOW the intercept — for every 1 unit right, the line drops 1 unit.",
        ],
      },
      {
        id: 'lin-4',
        stepNumber: 4,
        title: 'Fractional gradient',
        instruction: 'Draw the straight line.',
        equation: 'y = ½x − 2',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { slope: 0.5, intercept: -2 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Fractional gradient',
        hints: [
          "y-intercept c = −2 — drag the intercept handle below the x-axis to −2.",
          "Gradient ½ means for every 2 units right the line rises 1. Drag slope handle slightly above the intercept point.",
        ],
      },
    ],
  },

  // ── Topic 3: Quadratic Graphs ────────────────────────────────────────────────
  {
    id: 'quadratic-graphs',
    title: 'Quadratic Graphs — Vertex Form',
    subjectId: 'zol-mathematics',
    description: 'Shape parabolas by placing the vertex and adjusting the coefficient a in y = a(x − h)² + k',
    steps: [
      {
        id: 'quad-1',
        stepNumber: 1,
        title: 'Basic parabola',
        instruction: 'Draw the parabola.',
        equation: 'y = x²',
        widgetType: 'quadratic-graph',
        widgetConfig: { gridRange: 5 },
        correctState: { a: 1, h: 0, k: 0 },
        tolerance: { a: 0.2, h: 0.4, k: 0.4 },
        milestone: 'Vertex at the origin',
        hints: [
          "y = x² is y = 1(x − 0)² + 0. The vertex is at the origin (0, 0).",
          "Place the vertex at (0, 0). With a = 1 the parabola opens upward — the width handle sits 1 unit above the vertex at (1, 1).",
        ],
      },
      {
        id: 'quad-2',
        stepNumber: 2,
        title: 'Shifted vertex',
        instruction: 'Draw the parabola.',
        equation: 'y = (x − 2)² − 1',
        widgetType: 'quadratic-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { a: 1, h: 2, k: -1 },
        tolerance: { a: 0.2, h: 0.4, k: 0.4 },
        milestone: 'Shifted vertex',
        hints: [
          "Compare with y = a(x − h)² + k. Here h = 2, k = −1.",
          "Drag the vertex to (2, −1). a = 1 so the parabola opens upward with the same shape as y = x².",
        ],
      },
      {
        id: 'quad-3',
        stepNumber: 3,
        title: 'Downward parabola',
        instruction: 'Draw the parabola.',
        equation: 'y = −(x + 1)² + 4',
        widgetType: 'quadratic-graph',
        widgetConfig: { gridRange: 7 },
        correctState: { a: -1, h: -1, k: 4 },
        tolerance: { a: 0.2, h: 0.4, k: 0.4 },
        milestone: 'Downward parabola',
        hints: [
          "(x + 1)² = (x − (−1))², so h = −1. The negative a means the parabola opens downward.",
          "Vertex at (−1, 4). Drag the width handle BELOW the vertex to show a is negative.",
        ],
      },
      {
        id: 'quad-4',
        stepNumber: 4,
        title: 'Narrow parabola',
        instruction: 'Draw the parabola.',
        equation: 'y = 2(x − 1)² − 3',
        widgetType: 'quadratic-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { a: 2, h: 1, k: -3 },
        tolerance: { a: 0.25, h: 0.4, k: 0.4 },
        milestone: 'Narrow parabola',
        hints: [
          "h = 1, k = −3 → vertex at (1, −3). a = 2 makes the parabola narrower than y = x².",
          "Drag the width handle to (2, 2+−3) = (2, −1). It sits 2 units above the vertex.",
        ],
      },
    ],
  },

  // ── Topic 4: Angles in Geometry ──────────────────────────────────────────────
  {
    id: 'angles-geometry',
    title: 'Angles in Geometry',
    subjectId: 'zol-mathematics',
    description: 'Apply ZIMSEC angle properties — acute, supplementary, triangles, and angles at a point',
    steps: [
      {
        id: 'ang-1',
        stepNumber: 1,
        title: 'Acute angle',
        instruction: 'Draw an acute angle of 55°.',
        widgetType: 'angle',
        widgetConfig: { gridRange: 180 },
        correctState: { angleDeg: 55 },
        tolerance: { angleDeg: 4 },
        milestone: 'Acute angle',
        hints: [
          "An acute angle is between 0° and 90°. Drag the arm to 55° — just over halfway to 90°.",
          "55° is on the left side of the protractor's first quarter. Look for the 55 label.",
        ],
      },
      {
        id: 'ang-2',
        stepNumber: 2,
        title: 'Supplementary angles',
        instruction: 'Angles on a straight line sum to 180°. One angle is 65°. Draw the other angle.',
        widgetType: 'angle',
        widgetConfig: { gridRange: 180 },
        correctState: { angleDeg: 115 },
        tolerance: { angleDeg: 4 },
        milestone: 'Supplementary angles',
        hints: [
          "Supplementary angles add to 180°. So the missing angle = 180° − 65°.",
          "180° − 65° = 115°. Drag the arm past 90° to 115°.",
        ],
      },
      {
        id: 'ang-3',
        stepNumber: 3,
        title: 'Triangle angle sum',
        instruction: 'A triangle has two angles of 70° and 45°. Draw the third angle.',
        widgetType: 'angle',
        widgetConfig: { gridRange: 180 },
        correctState: { angleDeg: 65 },
        tolerance: { angleDeg: 4 },
        milestone: 'Triangle angle sum',
        hints: [
          "Interior angles of a triangle always sum to 180°.",
          "70° + 45° = 115°. Third angle = 180° − 115° = 65°. Draw 65°.",
        ],
      },
      {
        id: 'ang-4',
        stepNumber: 4,
        title: 'Angles at a point',
        instruction: 'Four angles meet at a point. Three are 98°, 76°, and 52°. Draw the fourth angle.',
        widgetType: 'angle',
        widgetConfig: { gridRange: 360 },
        correctState: { angleDeg: 134 },
        tolerance: { angleDeg: 4 },
        milestone: 'Angles at a point',
        hints: [
          "Angles at a point add up to 360°.",
          "98° + 76° + 52° = 226°. Fourth angle = 360° − 226° = 134°.",
        ],
      },
    ],
  },

  // ── Topic 5: Pythagoras Theorem ──────────────────────────────────────────────
  {
    id: 'pythagoras-theorem',
    title: 'Pythagoras Theorem',
    subjectId: 'zol-mathematics',
    description: 'Build right triangles and find missing sides using a² + b² = c²',
    steps: [
      {
        id: 'pyth-1',
        stepNumber: 1,
        title: '3-4-5 triangle',
        instruction: 'Set up the right triangle with legs 3 cm and 4 cm.',
        equation: 'a² + b² = c²',
        widgetType: 'pythagoras',
        widgetConfig: { gridRange: 10 },
        correctState: { a: 3, b: 4 },
        tolerance: { side: 0.6 },
        milestone: '3-4-5 triangle',
        hints: [
          "Drag the base (horizontal) handle right until a = 3.",
          "Then drag the height handle up until b = 4. Watch the hypotenuse — it will equal 5!",
        ],
      },
      {
        id: 'pyth-2',
        stepNumber: 2,
        title: '5-12-13 triangle',
        instruction: 'Set up the right triangle with legs 5 cm and 12 cm.',
        equation: 'c = √(5² + 12²)',
        widgetType: 'pythagoras',
        widgetConfig: { gridRange: 14 },
        correctState: { a: 5, b: 12 },
        tolerance: { side: 0.6 },
        milestone: '5-12-13 triangle',
        hints: [
          "Set base a = 5 and height b = 12.",
          "c = √(25 + 144) = √169 = 13. Check the hypotenuse label as you drag.",
        ],
      },
      {
        id: 'pyth-3',
        stepNumber: 3,
        title: 'Find the missing leg',
        instruction: 'A ladder 10 m long leans against a wall, base 6 m from the wall. How high does it reach? Set base = 6.',
        equation: '6² + b² = 10²',
        widgetType: 'pythagoras',
        widgetConfig: { gridRange: 12 },
        correctState: { a: 6, b: 8 },
        tolerance: { side: 0.6 },
        milestone: 'Finding a leg',
        hints: [
          "c = 10 (the ladder), a = 6 (base distance). Solve for b: b² = 100 − 36 = 64.",
          "b = √64 = 8 m. Drag height to 8 and base to 6.",
        ],
      },
      {
        id: 'pyth-4',
        stepNumber: 4,
        title: 'Real-world diagonal',
        instruction: 'A TV screen is 16 cm wide and 12 cm tall. Set up the triangle to find the diagonal.',
        equation: 'c = √(16² + 12²)',
        widgetType: 'pythagoras',
        widgetConfig: { gridRange: 20 },
        correctState: { a: 16, b: 12 },
        tolerance: { side: 0.7 },
        milestone: 'Real-world application',
        hints: [
          "The screen width is the base (a = 16) and the height is b = 12.",
          "c = √(256 + 144) = √400 = 20 cm. Drag base to 16 and height to 12 to confirm.",
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // PHYSICS (zol-physics)
  // ════════════════════════════════════════════════════════════════════════════

  // ── Topic 6: Distance-Time Graphs ────────────────────────────────────────────
  {
    id: 'distance-time-graphs',
    title: 'Distance-Time Graphs',
    subjectId: 'zol-physics',
    description: 'Draw d-t graphs for objects moving at constant speed — the gradient equals speed',
    steps: [
      {
        id: 'dt-1',
        stepNumber: 1,
        title: 'Constant speed: 2 m/s',
        instruction: 'Draw the distance-time graph for an object moving at 2 m/s.',
        equation: 'd = 2t',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6, xLabel: 'Time (s)', yLabel: 'Distance (m)' },
        correctState: { slope: 2, intercept: 0 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Speed = gradient',
        hints: [
          "On a d-t graph the gradient (slope) equals speed. Here speed = 2 m/s.",
          "The object starts at d = 0 when t = 0. Drag intercept to 0, then set the slope to 2.",
        ],
      },
      {
        id: 'dt-2',
        stepNumber: 2,
        title: 'Faster: 5 m/s',
        instruction: 'Draw the d-t graph for an object moving at 5 m/s.',
        equation: 'd = 5t',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { slope: 5, intercept: 0 },
        tolerance: { slope: 0.2, intercept: 0.35 },
        milestone: 'Steeper = faster',
        hints: [
          "A steeper line means higher speed. Speed = 5 m/s so the gradient must be 5.",
          "Keep intercept at 0 (object starts at origin) and drag slope handle higher.",
        ],
      },
      {
        id: 'dt-3',
        stepNumber: 3,
        title: 'Already 4 m away',
        instruction: 'An object is 4 m from a sensor and moves away at 1 m/s. Draw its d-t graph.',
        equation: 'd = t + 4',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { slope: 1, intercept: 4 },
        tolerance: { slope: 0.15, intercept: 0.4 },
        milestone: 'Non-zero start',
        hints: [
          "The y-intercept is the starting distance — here 4 m. Drag intercept handle to 4.",
          "Speed = 1 m/s → gradient = 1. Both intercept (4) and slope (1) must match.",
        ],
      },
      {
        id: 'dt-4',
        stepNumber: 4,
        title: 'Slow speed: 0.5 m/s',
        instruction: 'Draw the d-t graph for an object moving at 0.5 m/s from the origin.',
        equation: 'd = 0.5t',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 7 },
        correctState: { slope: 0.5, intercept: 0 },
        tolerance: { slope: 0.12, intercept: 0.35 },
        milestone: 'Slow speed — shallow slope',
        hints: [
          "A shallow slope means slow speed. 0.5 m/s rises 1 m every 2 seconds.",
          "Intercept = 0 (starts at origin). Slope handle should be only slightly above the intercept.",
        ],
      },
    ],
  },

  // ── Topic 7: Ohm's Law ───────────────────────────────────────────────────────
  {
    id: 'ohms-law',
    title: "Ohm's Law — V = IR",
    subjectId: 'zol-physics',
    description: 'Plot voltage against current to find resistance from the gradient of a V-I graph',
    steps: [
      {
        id: 'ohm-1',
        stepNumber: 1,
        title: 'R = 2 Ω',
        instruction: 'Plot the V-I graph for a resistor of 2 Ω.',
        equation: 'V = 2I',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: 2, intercept: 0 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Gradient = resistance',
        hints: [
          "V = IR, so V = 2I. On a V-I graph, gradient = resistance (R).",
          "The graph passes through the origin (no voltage when no current). Set gradient to 2.",
        ],
      },
      {
        id: 'ohm-2',
        stepNumber: 2,
        title: 'R = 5 Ω',
        instruction: 'Plot the V-I graph for a 5 Ω resistor.',
        equation: 'V = 5I',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { slope: 5, intercept: 0 },
        tolerance: { slope: 0.2, intercept: 0.35 },
        milestone: 'Higher resistance',
        hints: [
          "A higher resistance gives a steeper line — more voltage needed per amp of current.",
          "Gradient = 5. Drag slope handle significantly upward and keep intercept at 0.",
        ],
      },
      {
        id: 'ohm-3',
        stepNumber: 3,
        title: 'R = 1 Ω',
        instruction: 'Plot the V-I graph for a 1 Ω resistor.',
        equation: 'V = I',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 5 },
        correctState: { slope: 1, intercept: 0 },
        tolerance: { slope: 0.12, intercept: 0.35 },
        milestone: '1 Ω — 45° line',
        hints: [
          "R = 1 Ω means V = I. The gradient is exactly 1 — a 45° line through the origin.",
          "Slope = 1, intercept = 0. This is the simplest case.",
        ],
      },
      {
        id: 'ohm-4',
        stepNumber: 4,
        title: 'Finding R from the graph',
        instruction: 'A device shows V = 10 V when I = 2 A. What is R? Plot the correct line.',
        equation: 'R = V ÷ I = 5 Ω',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 8 },
        correctState: { slope: 5, intercept: 0 },
        tolerance: { slope: 0.2, intercept: 0.35 },
        milestone: 'Calculating R from graph',
        hints: [
          "R = V ÷ I = 10 ÷ 2 = 5 Ω. So the gradient of the V-I graph = 5.",
          "Draw a line through the origin with gradient 5. The slope handle should be at height 5 above baseline.",
        ],
      },
    ],
  },

  // ── Topic 8: pH Scale ─────────────────────────────────────────────────────────
  // ════════════════════════════════════════════════════════════════════════════
  // CHEMISTRY (zol-chemistry)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'ph-scale',
    title: 'The pH Scale',
    subjectId: 'zol-chemistry',
    description: 'Classify solutions as acidic, neutral or alkaline using the pH scale (0–14)',
    steps: [
      {
        id: 'ph-1',
        stepNumber: 1,
        title: 'Neutral solution',
        instruction: 'Pure water is neutral. Drag the marker to the neutral pH.',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 14,
          min: 0, max: 14, unit: '',
          zones: [
            { min: 0, max: 6.9, color: '#ef4444', label: 'Acid' },
            { min: 6.9, max: 7.1, color: '#22c55e', label: 'Neutral' },
            { min: 7.1, max: 14, color: '#3b82f6', label: 'Alkali' },
          ],
        },
        correctState: { value: 7 },
        tolerance: { value: 0.5 },
        milestone: 'Neutral = pH 7',
        hints: [
          "Neutral solutions have pH exactly 7 — right in the middle of the scale.",
          "Drag the marker to 7. It should land in the green neutral zone.",
        ],
      },
      {
        id: 'ph-2',
        stepNumber: 2,
        title: 'Strong acid',
        instruction: 'Concentrated hydrochloric acid (HCl) has a very low pH. Place it correctly.',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 14,
          min: 0, max: 14, unit: '',
          zones: [
            { min: 0, max: 6.9, color: '#ef4444', label: 'Acid' },
            { min: 6.9, max: 7.1, color: '#22c55e', label: 'Neutral' },
            { min: 7.1, max: 14, color: '#3b82f6', label: 'Alkali' },
          ],
        },
        correctState: { value: 1 },
        tolerance: { value: 0.5 },
        milestone: 'Strong acid',
        hints: [
          "Strong acids like HCl have pH close to 0 — very acidic, deep in the red zone.",
          "Concentrated HCl is approximately pH 1. Drag the marker to the far left.",
        ],
      },
      {
        id: 'ph-3',
        stepNumber: 3,
        title: 'Strong alkali',
        instruction: 'Sodium hydroxide (NaOH) is a strong alkali. Place it on the scale.',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 14,
          min: 0, max: 14, unit: '',
          zones: [
            { min: 0, max: 6.9, color: '#ef4444', label: 'Acid' },
            { min: 6.9, max: 7.1, color: '#22c55e', label: 'Neutral' },
            { min: 7.1, max: 14, color: '#3b82f6', label: 'Alkali' },
          ],
        },
        correctState: { value: 13 },
        tolerance: { value: 0.5 },
        milestone: 'Strong alkali',
        hints: [
          "Strong alkalis have pH close to 14 — the right end of the scale.",
          "NaOH solution is approximately pH 13. Drag the marker near the right end.",
        ],
      },
      {
        id: 'ph-4',
        stepNumber: 4,
        title: 'Weak acid — vinegar',
        instruction: 'Vinegar (ethanoic acid) is a weak acid. Place it on the pH scale.',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 14,
          min: 0, max: 14, unit: '',
          zones: [
            { min: 0, max: 6.9, color: '#ef4444', label: 'Acid' },
            { min: 6.9, max: 7.1, color: '#22c55e', label: 'Neutral' },
            { min: 7.1, max: 14, color: '#3b82f6', label: 'Alkali' },
          ],
        },
        correctState: { value: 4 },
        tolerance: { value: 0.6 },
        milestone: 'Weak acid vs strong acid',
        hints: [
          "Weak acids have higher pH than strong acids — closer to 7 but still acidic.",
          "Vinegar is approximately pH 3–4. Drag to around 4 in the red (acid) zone.",
        ],
      },
    ],
  },

  // ── Topic 9: Atomic Number & Electron Configuration ───────────────────────────
  {
    id: 'atomic-structure',
    title: 'Atomic Number & Electron Configuration',
    subjectId: 'zol-chemistry',
    description: 'Use the periodic table to identify elements by their atomic number',
    steps: [
      {
        id: 'at-1',
        stepNumber: 1,
        title: 'Hydrogen',
        instruction: 'Hydrogen has 1 proton. Drag the marker to its atomic number.',
        equation: 'Atomic number = number of protons',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 20, min: 1, max: 20, unit: '',
          zones: [
            { min: 1, max: 2, color: '#f59e0b', label: 'Period 1' },
            { min: 3, max: 10, color: '#6366f1', label: 'Period 2' },
            { min: 11, max: 18, color: '#0d9488', label: 'Period 3' },
            { min: 19, max: 20, color: '#f97316', label: 'Period 4' },
          ],
        },
        correctState: { value: 1 },
        tolerance: { value: 0.5 },
        milestone: 'Hydrogen — smallest element',
        hints: [
          "The atomic number is the number of protons in the nucleus. Hydrogen has just 1 proton.",
          "Drag the marker all the way to the left — atomic number 1.",
        ],
      },
      {
        id: 'at-2',
        stepNumber: 2,
        title: 'Carbon',
        instruction: 'Carbon has 6 protons. Mark its atomic number on the scale.',
        equation: 'Carbon (C): Atomic number = 6',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 20, min: 1, max: 20, unit: '',
          zones: [
            { min: 1, max: 2, color: '#f59e0b', label: 'Period 1' },
            { min: 3, max: 10, color: '#6366f1', label: 'Period 2' },
            { min: 11, max: 18, color: '#0d9488', label: 'Period 3' },
            { min: 19, max: 20, color: '#f97316', label: 'Period 4' },
          ],
        },
        correctState: { value: 6 },
        tolerance: { value: 0.5 },
        milestone: 'Carbon — Period 2',
        hints: [
          "Carbon (C) has 6 protons → atomic number 6. It's in Period 2.",
          "Drag to 6 in the purple Period 2 zone.",
        ],
      },
      {
        id: 'at-3',
        stepNumber: 3,
        title: 'Sodium',
        instruction: 'Sodium (Na) has atomic number 11. Place it on the scale.',
        equation: 'Na: electron config 2, 8, 1',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 20, min: 1, max: 20, unit: '',
          zones: [
            { min: 1, max: 2, color: '#f59e0b', label: 'Period 1' },
            { min: 3, max: 10, color: '#6366f1', label: 'Period 2' },
            { min: 11, max: 18, color: '#0d9488', label: 'Period 3' },
            { min: 19, max: 20, color: '#f97316', label: 'Period 4' },
          ],
        },
        correctState: { value: 11 },
        tolerance: { value: 0.5 },
        milestone: 'Sodium — Period 3',
        hints: [
          "Sodium has 11 protons — it's in Period 3, the third row of the periodic table.",
          "Drag to 11, entering the teal Period 3 zone.",
        ],
      },
      {
        id: 'at-4',
        stepNumber: 4,
        title: 'Calcium',
        instruction: 'Calcium (Ca) is important for bones. It has atomic number 20. Mark it.',
        equation: 'Ca: electron config 2, 8, 8, 2',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 20, min: 1, max: 20, unit: '',
          zones: [
            { min: 1, max: 2, color: '#f59e0b', label: 'Period 1' },
            { min: 3, max: 10, color: '#6366f1', label: 'Period 2' },
            { min: 11, max: 18, color: '#0d9488', label: 'Period 3' },
            { min: 19, max: 20, color: '#f97316', label: 'Period 4' },
          ],
        },
        correctState: { value: 20 },
        tolerance: { value: 0.5 },
        milestone: 'Calcium — Period 4',
        hints: [
          "Ca has 20 protons → far right of the scale at atomic number 20.",
          "Drag all the way to 20, in the orange Period 4 zone.",
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // BIOLOGY (zol-biology)
  // ════════════════════════════════════════════════════════════════════════════

  // ── Topic 10: Microscope Magnification ──────────────────────────────────────
  {
    id: 'microscope-magnification',
    title: 'Microscope Magnification',
    subjectId: 'zol-biology',
    description: 'Calculate and set magnification values — the key skill for ZIMSEC Biology practical papers',
    steps: [
      {
        id: 'mag-1',
        stepNumber: 1,
        title: 'Low power: ×10',
        instruction: 'A cell appears 1 mm large but is actually 0.1 mm. Set the magnification used.',
        equation: 'M = image size ÷ actual size',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 500, min: 1, max: 500, unit: '×',
          zones: [
            { min: 1, max: 40, color: '#4ade80', label: 'Low power' },
            { min: 40, max: 100, color: '#f59e0b', label: 'Medium' },
            { min: 100, max: 500, color: '#f43f5e', label: 'High power' },
          ],
        },
        correctState: { value: 10 },
        tolerance: { value: 1 },
        milestone: 'Low-power objective',
        hints: [
          "M = image ÷ actual = 1 mm ÷ 0.1 mm = 10. Drag the marker to ×10.",
          "This is in the low-power range (green zone), typically the ×4 or ×10 objective.",
        ],
      },
      {
        id: 'mag-2',
        stepNumber: 2,
        title: 'Medium power: ×40',
        instruction: 'A cell is 0.025 mm actual size but appears 1 mm. Set the magnification.',
        equation: 'M = 1 ÷ 0.025 = 40',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 500, min: 1, max: 500, unit: '×',
          zones: [
            { min: 1, max: 40, color: '#4ade80', label: 'Low power' },
            { min: 40, max: 100, color: '#f59e0b', label: 'Medium' },
            { min: 100, max: 500, color: '#f43f5e', label: 'High power' },
          ],
        },
        correctState: { value: 40 },
        tolerance: { value: 2 },
        milestone: 'Medium-power objective',
        hints: [
          "M = 1 ÷ 0.025 = 40. This sits right at the boundary of low and medium power.",
          "Drag to ×40 — the amber medium-power zone.",
        ],
      },
      {
        id: 'mag-3',
        stepNumber: 3,
        title: 'Total magnification: eyepiece × objective',
        instruction: 'Eyepiece = ×10, objective = ×40. Set the total magnification.',
        equation: 'Total M = 10 × 40 = 400',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 500, min: 1, max: 500, unit: '×',
          zones: [
            { min: 1, max: 40, color: '#4ade80', label: 'Low power' },
            { min: 40, max: 100, color: '#f59e0b', label: 'Medium' },
            { min: 100, max: 500, color: '#f43f5e', label: 'High power' },
          ],
        },
        correctState: { value: 400 },
        tolerance: { value: 5 },
        milestone: 'Total magnification',
        hints: [
          "Total magnification = eyepiece × objective = 10 × 40 = 400.",
          "Drag to ×400, well into the high-power (red) zone.",
        ],
      },
      {
        id: 'mag-4',
        stepNumber: 4,
        title: 'Find actual size',
        instruction: 'At ×500 magnification, an image measures 5 mm. What is the actual size? Set that magnification.',
        equation: 'Actual = image ÷ M = 5 ÷ 500 = 0.01 mm',
        widgetType: 'number-line',
        widgetConfig: {
          gridRange: 500, min: 1, max: 500, unit: '×',
          zones: [
            { min: 1, max: 40, color: '#4ade80', label: 'Low power' },
            { min: 40, max: 100, color: '#f59e0b', label: 'Medium' },
            { min: 100, max: 500, color: '#f43f5e', label: 'High power' },
          ],
        },
        correctState: { value: 500 },
        tolerance: { value: 5 },
        milestone: 'High-power mastery',
        hints: [
          "We are told M = 500. Drag to the far right — ×500 is maximum high power.",
          "Actual size = 5 ÷ 500 = 0.01 mm. Confirm the magnification is ×500.",
        ],
      },
    ],
  },

  // ── Topic 11: Photosynthesis Rate ────────────────────────────────────────────
  {
    id: 'photosynthesis-rate',
    title: 'Photosynthesis & Light Intensity',
    subjectId: 'zol-biology',
    description: 'Explore how light intensity affects the rate of photosynthesis using linear graphs',
    steps: [
      {
        id: 'phot-1',
        stepNumber: 1,
        title: 'Direct proportionality',
        instruction: 'When light doubles, rate of photosynthesis doubles. Plot rate vs light intensity (slope = 1.5).',
        equation: 'Rate = 1.5 × Light intensity',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: 1.5, intercept: 0 },
        tolerance: { slope: 0.2, intercept: 0.4 },
        milestone: 'Proportionality',
        hints: [
          "Rate is directly proportional to light intensity (before light saturation). The line passes through the origin.",
          "Gradient = 1.5. Drag slope handle up — for every 2 units of light, rate increases by 3.",
        ],
      },
      {
        id: 'phot-2',
        stepNumber: 2,
        title: 'Effect of CO₂ concentration',
        instruction: 'Higher CO₂ gives a steeper rate increase (slope = 3). Plot this graph.',
        equation: 'Rate = 3 × Light intensity',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: 3, intercept: 0 },
        tolerance: { slope: 0.2, intercept: 0.4 },
        milestone: 'CO₂ as limiting factor',
        hints: [
          "More CO₂ means the plant can fix more carbon per unit of light — steeper gradient.",
          "Slope = 3, intercept = 0. Drag slope handle to give 3× rate increase per unit light.",
        ],
      },
      {
        id: 'phot-3',
        stepNumber: 3,
        title: 'Low temperature limits',
        instruction: 'At low temperature the rate is slower (slope = 0.5). Plot the low-temperature graph.',
        equation: 'Rate = 0.5 × Light intensity',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 6 },
        correctState: { slope: 0.5, intercept: 0 },
        tolerance: { slope: 0.12, intercept: 0.35 },
        milestone: 'Temperature as limiting factor',
        hints: [
          "Cold temperatures slow enzyme activity — the same light gives a smaller rate increase.",
          "Slope = 0.5 — a shallower line than before. Drag slope handle slightly above horizontal.",
        ],
      },
      {
        id: 'phot-4',
        stepNumber: 4,
        title: 'Comparing conditions',
        instruction: 'Plot the optimal conditions line: rate = 2 × light intensity (starting from 0).',
        equation: 'Rate = 2 × Light intensity',
        widgetType: 'linear-graph',
        widgetConfig: { gridRange: 7 },
        correctState: { slope: 2, intercept: 0 },
        tolerance: { slope: 0.15, intercept: 0.35 },
        milestone: 'Optimal conditions',
        hints: [
          "Optimal conditions: moderate CO₂, warm temperature, good light. Gradient = 2.",
          "Slope = 2, intercept = 0. This should be steeper than the 1.5 graph but not as steep as 3.",
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // GEOGRAPHY (zol-geography)
  // ════════════════════════════════════════════════════════════════════════════

  // ── Topic 12: Climate Graphs — Harare ────────────────────────────────────────
  {
    id: 'climate-graphs-harare',
    title: 'Climate Graphs — Harare, Zimbabwe',
    subjectId: 'zol-geography',
    description: 'Read and construct climate graphs for Zimbabwe using monthly temperature data',
    steps: [
      {
        id: 'clim-1',
        stepNumber: 1,
        title: 'Wet season temperatures',
        instruction: 'Harare is warmest in October and November. Drag bars to the correct temperatures (°C): Oct=26, Nov=25, Dec=24, Jan=23.',
        equation: 'Mean monthly temperature (°C)',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 40,
          labels: ['Oct', 'Nov', 'Dec', 'Jan'],
          yMax: 40, yLabel: 'Temp (°C)',
          barColor: '#f97316',
          barTolerance: 2,
        },
        correctState: { bars: [26, 25, 24, 23] },
        tolerance: { barTolerance: 2 },
        milestone: 'Wet season peak',
        hints: [
          "Zimbabwe's wet season (Oct-Jan) is the hottest. October peaks at about 26°C.",
          "Set Oct=26, Nov=25, Dec=24, Jan=23. Drag each bar's handle to the correct height.",
        ],
      },
      {
        id: 'clim-2',
        stepNumber: 2,
        title: 'Cool dry season',
        instruction: 'Harare\'s cool dry season: May=18°C, Jun=15°C, Jul=15°C, Aug=18°C.',
        equation: 'Mean monthly temperature (°C)',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 40,
          labels: ['May', 'Jun', 'Jul', 'Aug'],
          yMax: 40, yLabel: 'Temp (°C)',
          barColor: '#38bdf8',
          barTolerance: 2,
        },
        correctState: { bars: [18, 15, 15, 18] },
        tolerance: { barTolerance: 2 },
        milestone: 'Cool dry season',
        hints: [
          "June and July are coolest in Zimbabwe — temperatures drop to around 15°C.",
          "The pattern is symmetric: May and August both ≈18°C, with June and July both ≈15°C.",
        ],
      },
      {
        id: 'clim-3',
        stepNumber: 3,
        title: 'Monthly rainfall — wet season',
        instruction: 'Harare rainfall (mm): Nov=120, Dec=190, Jan=210, Feb=170. Drag bars to match.',
        equation: 'Monthly rainfall (mm)',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 250,
          labels: ['Nov', 'Dec', 'Jan', 'Feb'],
          yMax: 250, yLabel: 'Rainfall (mm)',
          barColor: '#6366f1',
          barTolerance: 15,
        },
        correctState: { bars: [120, 190, 210, 170] },
        tolerance: { barTolerance: 15 },
        milestone: 'Wet season rainfall',
        hints: [
          "January is the wettest month in Zimbabwe — peak rainfall around 210 mm.",
          "Set Nov=120, Dec=190, Jan=210 (tallest), Feb=170.",
        ],
      },
      {
        id: 'clim-4',
        stepNumber: 4,
        title: 'Dry season rainfall',
        instruction: 'In the dry season, rainfall is near zero: Jun=0, Jul=0, Aug=2, Sep=6 mm.',
        equation: 'Monthly rainfall (mm)',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 250,
          labels: ['Jun', 'Jul', 'Aug', 'Sep'],
          yMax: 250, yLabel: 'Rainfall (mm)',
          barColor: '#94a3b8',
          barTolerance: 4,
        },
        correctState: { bars: [0, 0, 2, 6] },
        tolerance: { barTolerance: 4 },
        milestone: 'Dry season mastery',
        hints: [
          "Zimbabwe has a true dry season — June and July can have zero rainfall.",
          "Set Jun=0, Jul=0, Aug=2, Sep=6. The bars should be very short or zero.",
        ],
      },
    ],
  },

  // ── Topic 13: Population Change ──────────────────────────────────────────────
  {
    id: 'population-change',
    title: 'Population Change',
    subjectId: 'zol-geography',
    description: 'Analyse birth rates, death rates and natural increase to understand Zimbabwe population trends',
    steps: [
      {
        id: 'pop-1',
        stepNumber: 1,
        title: 'Birth and death rates',
        instruction: 'In 2000, Zimbabwe had: birth rate = 38, death rate = 22, natural increase = 16 (per 1000). Set these bars.',
        equation: 'Natural increase = Birth rate − Death rate',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 60,
          labels: ['Birth rate', 'Death rate', 'Nat. increase'],
          yMax: 60, yLabel: 'Rate per 1000',
          barColor: '#4ade80',
          barTolerance: 3,
        },
        correctState: { bars: [38, 22, 16] },
        tolerance: { barTolerance: 3 },
        milestone: 'Natural increase formula',
        hints: [
          "Natural increase = birth rate − death rate = 38 − 22 = 16.",
          "Set: birth=38, death=22, natural increase=16. The increase bar should be shortest.",
        ],
      },
      {
        id: 'pop-2',
        stepNumber: 2,
        title: 'Improved healthcare effect',
        instruction: 'Better healthcare drops death rate to 10, birth rate stays at 38. Set the new values and natural increase.',
        equation: 'Natural increase = 38 − 10 = 28',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 60,
          labels: ['Birth rate', 'Death rate', 'Nat. increase'],
          yMax: 60, yLabel: 'Rate per 1000',
          barColor: '#14b8a6',
          barTolerance: 3,
        },
        correctState: { bars: [38, 10, 28] },
        tolerance: { barTolerance: 3 },
        milestone: 'Healthcare reduces death rate',
        hints: [
          "When death rate falls but birth rate stays high, natural increase rises — rapid population growth.",
          "Set birth=38, death=10, natural increase = 38−10 = 28.",
        ],
      },
      {
        id: 'pop-3',
        stepNumber: 3,
        title: 'Demographic transition',
        instruction: 'Later, both rates fall: birth=18, death=8, natural increase=10. Set these bars.',
        equation: 'Low birth, low death → slow growth',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 60,
          labels: ['Birth rate', 'Death rate', 'Nat. increase'],
          yMax: 60, yLabel: 'Rate per 1000',
          barColor: '#a78bfa',
          barTolerance: 3,
        },
        correctState: { bars: [18, 8, 10] },
        tolerance: { barTolerance: 3 },
        milestone: 'Stage 4 — low growth',
        hints: [
          "In demographic transition Stage 4, both rates are low — population growth slows.",
          "Set birth=18, death=8, natural increase=10. All bars should be much shorter than before.",
        ],
      },
      {
        id: 'pop-4',
        stepNumber: 4,
        title: 'Stable population',
        instruction: 'Population stabilises when birth rate = death rate = 12. Natural increase = 0. Set these bars.',
        equation: 'Zero natural increase = stable population',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 60,
          labels: ['Birth rate', 'Death rate', 'Nat. increase'],
          yMax: 60, yLabel: 'Rate per 1000',
          barColor: '#f59e0b',
          barTolerance: 3,
        },
        correctState: { bars: [12, 12, 0] },
        tolerance: { barTolerance: 3 },
        milestone: 'Zero natural increase',
        hints: [
          "When birth rate equals death rate, natural increase = 0 and population is stable.",
          "Set both birth and death to 12, and natural increase to 0 (bar at ground level).",
        ],
      },
    ],
  },

  // ── Topic 14: Distillation (Chemistry) ──────────────────────────────────────
  {
    id: 'distillation-process',
    title: 'Distillation — Separating Mixtures',
    subjectId: 'zol-chemistry',
    description: 'Explore the distillation apparatus used to separate liquids by their boiling points',
    steps: [
      {
        id: 'dist-1',
        stepNumber: 1,
        title: 'The heat source',
        instruction: 'Click on the Bunsen burner — what does it do in distillation?',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'distillation', targetStage: 'burner' },
        correctState: { selectedStage: 'burner', visitedStages: [] },
        milestone: 'Role of the heat source',
        hints: [
          "The heat source is at the bottom of the apparatus — it starts the whole process.",
          "Look for the Bunsen Burner box at the base of the setup and click on it.",
        ],
      },
      {
        id: 'dist-2',
        stepNumber: 2,
        title: 'Vaporisation',
        instruction: 'Click on the distilling flask — what happens to the mixture inside?',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'distillation', targetStage: 'flask' },
        correctState: { selectedStage: 'flask', visitedStages: [] },
        milestone: 'Vaporisation in the flask',
        hints: [
          "The liquid mixture is heated in a round-bottomed container — find it above the burner.",
          "Look for the Distilling Flask on the left side of the diagram and click on it.",
        ],
      },
      {
        id: 'dist-3',
        stepNumber: 3,
        title: 'Condensation',
        instruction: 'Click on the Liebig condenser — how does it separate the vapour?',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'distillation', targetStage: 'condenser' },
        correctState: { selectedStage: 'condenser', visitedStages: [] },
        milestone: 'Condensation process',
        hints: [
          "The condenser uses cold water to turn vapour back into liquid — it is on the right side.",
          "Find the Liebig Condenser — the long tube with water flowing through it — and click on it.",
        ],
      },
      {
        id: 'dist-4',
        stepNumber: 4,
        title: 'Collection',
        instruction: 'Click on the receiving flask — what is collected here?',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'distillation', targetStage: 'receiver' },
        correctState: { selectedStage: 'receiver', visitedStages: [] },
        milestone: 'Collecting the distillate',
        hints: [
          "The final container collects the purified liquid at the end of the apparatus.",
          "Look for the Receiving Flask at the bottom right of the diagram and click on it.",
        ],
      },
    ],
  },

  // ── Topic 15: The Water Cycle (Geography) ────────────────────────────────────
  {
    id: 'water-cycle',
    title: 'The Water Cycle — How Rainfall is Made',
    subjectId: 'zol-geography',
    description: 'Trace how water moves between the ocean, atmosphere and land in Zimbabwe',
    steps: [
      {
        id: 'wc-1',
        stepNumber: 1,
        title: 'From water to vapour',
        instruction: 'Click on the stage where the sun turns liquid water into water vapour.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'water-cycle', targetStage: 'evaporation' },
        correctState: { selectedStage: 'evaporation', visitedStages: [] },
        milestone: 'Evaporation',
        hints: [
          "The sun provides energy to turn water from the lake or ocean into gas — look near the lake.",
          "Click on the Evaporation zone on the left side of the diagram, above the water.",
        ],
      },
      {
        id: 'wc-2',
        stepNumber: 2,
        title: 'Cloud formation',
        instruction: 'Click on the stage where water vapour turns back into water droplets and forms clouds.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'water-cycle', targetStage: 'condensation' },
        correctState: { selectedStage: 'condensation', visitedStages: [] },
        milestone: 'Condensation',
        hints: [
          "As water vapour rises and cools, it changes back into tiny droplets — this forms clouds.",
          "Click on the Condensation zone near the cloud in the upper middle of the diagram.",
        ],
      },
      {
        id: 'wc-3',
        stepNumber: 3,
        title: 'Rain falls',
        instruction: 'Click on the stage where water falls from clouds as rain, hail or snow.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'water-cycle', targetStage: 'precipitation' },
        correctState: { selectedStage: 'precipitation', visitedStages: [] },
        milestone: 'Precipitation',
        hints: [
          "When cloud droplets become too heavy, they fall to the ground as rain.",
          "Click on the Precipitation zone — the area below the cloud where rain drops fall.",
        ],
      },
      {
        id: 'wc-4',
        stepNumber: 4,
        title: 'Back to the sea',
        instruction: 'Click on the stage where water flows along the surface back to rivers and the ocean.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'water-cycle', targetStage: 'runoff' },
        correctState: { selectedStage: 'runoff', visitedStages: [] },
        milestone: 'Surface runoff',
        hints: [
          "After rain falls, water moves across the land surface back towards rivers and the sea.",
          "Click on the Surface Runoff zone along the bottom of the diagram.",
        ],
      },
    ],
  },

  // ── Topic 16: Types of Mining (Geography) ────────────────────────────────────
  {
    id: 'types-of-mining',
    title: 'Types of Mining in Zimbabwe',
    subjectId: 'zol-geography',
    description: 'Compare open-cast, shaft and alluvial mining methods used across Zimbabwe',
    steps: [
      {
        id: 'mine-1',
        stepNumber: 1,
        title: 'Near-surface minerals',
        instruction: 'Click on the type of mining where the mineral deposit is near the surface and a large pit is dug.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'mining', targetStage: 'open-cast' },
        correctState: { selectedStage: 'open-cast', visitedStages: [] },
        milestone: 'Open-cast mining',
        hints: [
          "This type removes surface soil and rock (overburden) to reach minerals just below the surface.",
          "Click on Open-cast Mining — the left panel showing a terraced pit shape.",
        ],
      },
      {
        id: 'mine-2',
        stepNumber: 2,
        title: 'Deep ore bodies',
        instruction: 'Click on the mining method that goes deep underground using a vertical shaft and horizontal tunnels.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'mining', targetStage: 'shaft' },
        correctState: { selectedStage: 'shaft', visitedStages: [] },
        milestone: 'Shaft mining',
        hints: [
          "When ore is very deep, miners dig a vertical shaft and branch out horizontally at different levels.",
          "Click on Shaft Mining — the middle panel showing vertical and horizontal tunnels underground.",
        ],
      },
      {
        id: 'mine-3',
        stepNumber: 3,
        title: 'Gold in river sediments',
        instruction: 'Click on the mining method where gold particles are found in riverbeds and washed sediment.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'mining', targetStage: 'alluvial' },
        correctState: { selectedStage: 'alluvial', visitedStages: [] },
        milestone: 'Alluvial mining',
        hints: [
          "Rivers carry and deposit minerals in their beds — this type of mining sifts sediment for gold.",
          "Click on Alluvial Mining — the right panel showing a river and gold panning.",
        ],
      },
      {
        id: 'mine-4',
        stepNumber: 4,
        title: 'Zimbabwe context',
        instruction: "Zimbabwe's Great Dyke platinum deposits are found near the surface in large quantities. Which mining method is used?",
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'mining', targetStage: 'open-cast' },
        correctState: { selectedStage: 'open-cast', visitedStages: [] },
        milestone: 'Great Dyke platinum mining',
        hints: [
          "The Great Dyke is a long ridge of mineral-rich rock — the deposits are accessible from the surface.",
          "When minerals are near the surface in large volumes, open-cast (open-pit) mining is most efficient.",
        ],
      },
    ],
  },

  // ── Topic 17: The Rock Cycle (Geography) ─────────────────────────────────────
  {
    id: 'rock-cycle',
    title: 'The Rock Cycle',
    subjectId: 'zol-geography',
    description: 'Discover how igneous, sedimentary and metamorphic rocks form and transform',
    steps: [
      {
        id: 'rock-1',
        stepNumber: 1,
        title: 'Molten rock',
        instruction: 'Click on the molten rock zone deep within the Earth that all rock types ultimately come from.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'rock-cycle', targetStage: 'magma' },
        correctState: { selectedStage: 'magma', visitedStages: [] },
        milestone: 'Understanding magma',
        hints: [
          "This molten material is found in the Earth's mantle. When it erupts from a volcano it is called lava.",
          "Click on the Magma zone — the red box in the lower centre of the triangle.",
        ],
      },
      {
        id: 'rock-2',
        stepNumber: 2,
        title: 'Volcanic rocks',
        instruction: 'Click on the rock type that forms when magma cools and solidifies — both underground and from volcanic eruptions.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'rock-cycle', targetStage: 'igneous' },
        correctState: { selectedStage: 'igneous', visitedStages: [] },
        milestone: 'Igneous rock formation',
        hints: [
          "This rock type forms from cooling magma or lava — granite and basalt are examples.",
          "Click on Igneous Rock — the orange box at the top of the diagram.",
        ],
      },
      {
        id: 'rock-3',
        stepNumber: 3,
        title: 'Layered rocks',
        instruction: 'Click on the rock type formed from compressed layers of sediment, shells and organic material over millions of years.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'rock-cycle', targetStage: 'sedimentary' },
        correctState: { selectedStage: 'sedimentary', visitedStages: [] },
        milestone: 'Sedimentary rock formation',
        hints: [
          "Rivers carry small rock fragments that settle in layers at the bottom of seas and lakes.",
          "Click on Sedimentary Rock — the amber box at the bottom left of the diagram.",
        ],
      },
      {
        id: 'rock-4',
        stepNumber: 4,
        title: 'Heat and pressure',
        instruction: 'Click on the rock type that forms when existing rocks are changed by extreme heat and pressure deep in the crust.',
        widgetType: 'process-diagram',
        widgetConfig: { gridRange: 1, diagramType: 'rock-cycle', targetStage: 'metamorphic' },
        correctState: { selectedStage: 'metamorphic', visitedStages: [] },
        milestone: 'Metamorphic rock formation',
        hints: [
          "When rocks are buried deep and squeezed by tectonic forces, they transform without melting.",
          "Click on Metamorphic Rock — the purple box at the bottom right of the diagram.",
        ],
      },
    ],
  },

  // ── Topic 18: Statistics — Central Tendency (Mathematics) ────────────────────
  {
    id: 'statistics-central-tendency',
    title: 'Statistics — Central Tendency',
    subjectId: 'zol-mathematics',
    description: 'Calculate mean, median and mode from frequency bar charts using Zimbabwe rainfall data',
    steps: [
      {
        id: 'stat-1',
        stepNumber: 1,
        title: 'Reading the mode',
        instruction: 'A class recorded daily rainfall (mm) over 5 days: 4, 7, 7, 9, 3. Drag bars to match, then identify the mode (most frequent value).',
        equation: 'Mode = most frequent value',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 10,
          labels: ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'],
          yMax: 10, yLabel: 'Rainfall (mm)',
          barColor: '#14b8a6',
          barTolerance: 1,
        },
        correctState: { bars: [4, 7, 7, 9, 3] },
        tolerance: { barTolerance: 1 },
        milestone: 'Identifying the mode',
        hints: [
          "Set each bar to the daily value: Day1=4, Day2=7, Day3=7, Day4=9, Day5=3.",
          "The mode is 7 because it appears twice — more than any other value. Build the chart to see this visually.",
        ],
      },
      {
        id: 'stat-2',
        stepNumber: 2,
        title: 'Calculating the mean',
        instruction: 'The monthly rainfall (mm) for Harare over 4 months: 120, 190, 80, 50. Drag bars to match. The mean = total ÷ number of months.',
        equation: 'Mean = (120 + 190 + 80 + 50) ÷ 4 = 110 mm',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 200,
          labels: ['Jan', 'Feb', 'Mar', 'Apr'],
          yMax: 200, yLabel: 'Rainfall (mm)',
          barColor: '#3b82f6',
          barTolerance: 5,
        },
        correctState: { bars: [120, 190, 80, 50] },
        tolerance: { barTolerance: 5 },
        milestone: 'Calculating the mean',
        hints: [
          "Set the bars: Jan=120, Feb=190, Mar=80, Apr=50. Add all values and divide by 4.",
          "Total = 440 mm. Mean = 440 ÷ 4 = 110 mm. The mean is not always equal to any single bar.",
        ],
      },
      {
        id: 'stat-3',
        stepNumber: 3,
        title: 'Finding the median',
        instruction: 'Scores in a maths test (5 students): 45, 62, 70, 55, 38. Drag bars to match. Find the median (middle value when sorted).',
        equation: 'Median: sort first → 38, 45, 55, 62, 70',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 100,
          labels: ['Ali', 'Beth', 'Chido', 'David', 'Eve'],
          yMax: 100, yLabel: 'Score (%)',
          barColor: '#a78bfa',
          barTolerance: 2,
        },
        correctState: { bars: [45, 62, 70, 55, 38] },
        tolerance: { barTolerance: 2 },
        milestone: 'Finding the median',
        hints: [
          "Set bars: Ali=45, Beth=62, Chido=70, David=55, Eve=38.",
          "Sort the scores: 38, 45, 55, 62, 70. The middle value (3rd of 5) is the median = 55.",
        ],
      },
      {
        id: 'stat-4',
        stepNumber: 4,
        title: 'Mean vs median',
        instruction: 'Population of 4 Zimbabwe towns (thousands): 12, 15, 11, 62. Drag bars to match. Compare mean and median to see which is better for skewed data.',
        equation: 'Mean = (12+15+11+62) ÷ 4 = 25 | Median = (12+15) ÷ 2 = 13.5',
        widgetType: 'bar-chart',
        widgetConfig: {
          gridRange: 70,
          labels: ['Town A', 'Town B', 'Town C', 'Town D'],
          yMax: 70, yLabel: 'Population (000s)',
          barColor: '#f97316',
          barTolerance: 2,
        },
        correctState: { bars: [12, 15, 11, 62] },
        tolerance: { barTolerance: 2 },
        milestone: 'Mean vs median for skewed data',
        hints: [
          "Set bars: A=12, B=15, C=11, D=62. Town D is an outlier — it is much larger than the others.",
          "Mean = 100 ÷ 4 = 25 (pulled high by Town D). Sorted: 11,12,15,62 → median = (12+15)÷2 = 13.5. The median better represents typical towns here.",
        ],
      },
    ],
  },
]

export function getTopic(id: string): LearningTopic | undefined {
  return LEARNING_TOPICS.find(t => t.id === id)
}

export function getTopicsForSubject(subjectId: string): LearningTopic[] {
  return LEARNING_TOPICS.filter(t => t.subjectId === subjectId)
}
